### ISSUE TITLE
where is cif2json?

### ISSUE THREAD

**Issue by wojdyr** [cod-developers/cod-tools#2]
Hi again,
your [paper](http://journals.iucr.org/j/issues/2016/01/00/po5052/index.html) says:

> COD::CIF::Parser enables the conversion of CIF format to other widely used lossless data formats (i.e. JSON, as implemented in cif2json from cod-tools)

Maybe I just can't see it, but where is this cif2json tool?

I'd like to use it to test a CIF parser that I'm writing now.
BTW JMol has similar utility:
https://sourceforge.net/p/jmol/mailman/message/35622017/
but having two opinions would be better.

**Comment by sauliusg** [comment]
On 2017-01-25 19:52, Marcin Wojdyr wrote:
> Hi again,
> your paper
> <http://journals.iucr.org/j/issues/2016/01/00/po5052/index.html> says:
> 
>     COD::CIF::Parser enables the conversion of CIF format to other
>     widely used lossless data formats (i.e. JSON, as implemented in
>     cif2json from cod-tools)
> 
> Maybe I just can't see it, but where is this cif2json tool?

Currently, it is in the ^/branches/andrius-cif2json branch. I'll have a
look at it (I guess everything is OK there), and then we merge it into
the ^/trunk.

Regards,
Saulius


-- 
Dr. Saulius Gražulis
Vilnius University Institute of Biotechnology, Saulėtekio al. 7
LT-10223 Vilnius, Lietuva (Lithuania)
fax: (+370-5)-2234367 / phone (office): (+370-5)-2234353
mobile: (+370-684)-49802, (+370-614)-36366

**Comment by sauliusg** [comment]
On 2017-01-25 19:52, Marcin Wojdyr wrote:
> I'd like to use it to test a CIF parser that I'm writing now.
> BTW JMol has similar utility:
> https://sourceforge.net/p/jmol/mailman/message/35622017/
> but having two opinions would be better.

Caveat emptor: the JSON which 'cif2json' from cod-tools will produce
will (most probably) be different from the JMol's json, obviously
because both were developed independently and there is no common schema
or dictionary for representing crystal structures in JSON (at last I do
not know about such schema at the moment).

Should we attempt to develop one?

At the moment we use JSON as an intermediate format for piping through
out tools, and essentially just dump out internal data structures in it.
If you want a standardised, long-lasting, archival format, CIF is
currently the way to go.

Regards,
Saulius

-- 
Dr. Saulius Gražulis
Vilnius University Institute of Biotechnology, Saulėtekio al. 7
LT-10223 Vilnius, Lietuva (Lithuania)
fax: (+370-5)-2234367 / phone (office): (+370-5)-2234353
mobile: (+370-684)-49802, (+370-614)-36366

**Comment by sauliusg** [comment]
On 2017-01-25 19:52, Marcin Wojdyr wrote:
> Hi again,
> your paper
> <http://journals.iucr.org/j/issues/2016/01/00/po5052/index.html> says:
> 
>     COD::CIF::Parser enables the conversion of CIF format to other
>     widely used lossless data formats (i.e. JSON, as implemented in
>     cif2json from cod-tools)
> 
> Maybe I just can't see it, but where is this cif2json tool?
> 
> I'd like to use it to test a CIF parser that I'm writing now.
> BTW JMol has similar utility:
> https://sourceforge.net/p/jmol/mailman/message/35622017/
> but having two opinions would be better.

We have now merged the 'cif2json' and 'json2cif' scripts into the trunk.
Also, many scripts (e.g. 'cif_filter', 'cif2cod') now support options
'--json-input' and '--json-output' and '--json' (for both JSON input and
output), whenever relevant.

commit b1b3f5a694ddfe2baa52b59c3fb6fc060422d52d
git-svn-id: svn://cod.ibt.lt/cod-tools/trunk@4827

Please have a look.

Sincerely yours,
Saulius

-- 
Dr. Saulius Gražulis
Vilnius University Institute of Biotechnology, Saulėtekio al. 7
LT-10223 Vilnius, Lietuva (Lithuania)
fax: (+370-5)-2234367 / phone (office): (+370-5)-2234353
mobile: (+370-684)-49802, (+370-614)-36366

**Comment by wojdyr** [comment]
Thanks! I tried cif2json, works as expected.

**Comment by sauliusg** [comment]
On 2017-01-30 18:23, Marcin Wojdyr wrote:
> Thanks! I tried cif2json, works as expected.

Great! Thanks for the message, and closing the issue.

I have noticed a caveat, though. If you pipe *a lot* of JSONS through
our current tools, they will try to keep all of them in RAM, and will
run out of memory at some stage. We'll change this behaviour to process
a JSON at a time and discard the data, so that you can pipe the whole
COD through cod-tools, and more :). For now, however, one has to resort
to '| xargs ...' construct to limit the number of files processed at once.

Regards,
Saulius

-- 
Dr. Saulius Gražulis
Vilnius University Institute of Biotechnology, Saulėtekio al. 7
LT-10223 Vilnius, Lietuva (Lithuania)
fax: (+370-5)-2234367 / phone (office): (+370-5)-2234353
mobile: (+370-684)-49802, (+370-614)-36366
