### ISSUE TITLE
pycodcif parser: numerical types are not handled

### ISSUE THREAD

**Issue by blokhin** [cod-developers/cod-tools#6]
The fields with the numerical values, such as **_cell_length_a**, **_atom_site_occupancy** _etc._, are represented as strings, but are in principle expected to be floats.

**Comment by blokhin** [comment]
BTW is it a proper place to ask questions and share experience on `pycodcif`?

S.G.> I think yes :)

**Comment by sauliusg** [comment]
One might argue that this is not a bug but a feature. Viz.:

- When parsing a file, the parser does not know (and SHOULD NOT (a la
RFC 2119) care) what types are mandated in the CIF dictionary.

So, 'data_X _cell_length_a five_point_seventy_two' is a syntactically
correct CIF, even though it is not valid according to cif_core.dic from
IUCr (but might be valid according to some other dictionary, btw). Since
the syntax is correct, we should be able to parse it with 'pycodcif' and
get the parse tree. The only universal way to represent data is string
values in this case.

On a practical side, when we ingest files from publications into the
COD, many files are not valid, even if they are syntactically correct
(that's life); rejecting files just because some types do not match
would cause us to loose too much useful data.

I suggest that a versatile procedure to read a CIF could be:

a/ parse an input file (using e.g.  pycodcif) and get the internal data
representation; optionally, instruct 'pycodcif' to correct syntax (not
needed for COD data ;

b/ validated the CIF and/or check data items types for those data items
that you are going to use;

c/ convert types to a suitable representation (e.g float). Perl does
this on the fly, so no special effort is needed; other programming
systems might need explicit conversion step;

d/ use the converted values if types are OK; raise exception otherwise.

Cheers,
Saulius

**Comment by blokhin** [comment]
OK, your reasoning makes sense to me. Spasibo.

**Comment by merkys** [comment]
In principle we could detect numeric data values and convert them to integers or floats in the parser level. However, by doing so for floats we run into a risk of loosing the precision. As told by @sauliusg, string -> numeric value conversion in Perl is completely transparent, therefore, strings in the output both preserve the original precision and are straightforwardly usable in the programs. Not sure how to have the same win-win situation in Python.
